# Emojis per a totes les skills (única font d'icones — sempre es renderitzen)
_EMOJI: dict[str, str] = {
    # Languages
    "python": "🐍",
    "r": "📊",
    "scala": "⚡",
    "java": "☕",
    "javascript": "🌐",
    "typescript": "🌐",
    "c#": "💜",
    "c++": "⚙️",
    "vb.net": "🔷",
    ".net": "🔷",
    "asp.net": "🔷",
    "ado.net": "🔷",
    "entity framework": "🔷",
    ".net framework": "🔷",
    # SQL / Data
    "sql": "🗄️",
    "postgresql": "🐘",
    "postgres": "🐘",
    "mysql": "🐬",
    "sqlite": "🗄️",
    "mongodb": "🍃",
    "redis": "🔴",
    "neo4j": "🔵",
    "elasticsearch": "🔍",
    # Data science / ML
    "pandas": "🐼",
    "numpy": "🔢",
    "matplotlib": "📈",
    "scikit-learn": "🤖",
    "sklearn": "🤖",
    "tensorflow": "🧠",
    "keras": "🧠",
    "pytorch": "🔥",
    "xgboost": "🚀",
    "mlflow": "⚙️",
    "pyspark": "⚡",
    "spark": "⚡",
    "dbt": "🔧",
    "databricks": "🧱",
    "kubeflow": "⚙️",
    "jupyter": "📓",
    # BI / Visualització
    "tableau": "📊",
    "power bi": "📊",
    "looker": "📊",
    "grafana": "📈",
    "google sheets": "📋",
    # Office / Microsoft
    "excel": "📗",
    "microsoft excel": "📗",
    "power query": "📗",
    "powerpoint": "📙",
    "word": "📘",
    "sharepoint": "🔗",
    # DevOps / Infraestructura
    "docker": "🐳",
    "kubernetes": "☸️",
    "airflow": "🌊",
    "kafka": "📨",
    "git": "🔀",
    "github": "🐙",
    "gitlab": "🦊",
    "linux": "🐧",
    "bash": "💻",
    "terraform": "🏗️",
    "ansible": "⚙️",
    "jenkins": "🔧",
    "ci/cd": "🔄",
    "pytest": "🧪",
    # Cloud
    "aws": "☁️",
    "aws/gcp": "☁️",
    "azure": "☁️",
    "gcp": "☁️",
    "snowflake": "❄️",
    # Web / Frontend
    "flask": "🌶️",
    "fastapi": "⚡",
    "django": "🎸",
    "react": "⚛️",
    "next.js": "▲",
    "html": "🌐",
    "css": "🎨",
    "bootstrap": "🅱️",
    "bootstrap css": "🅱️",
    "ajax": "⚡",
    "jquery": "💲",
    # Eines
    "jira": "📋",
    "confluence": "📝",
    "notion": "📝",
    "figma": "🎨",
    "linkedin": "💼",
    "visual studio": "💜",
    # ML / AI (sense CDN)
    "supervised machine learning": "🤖",
    "unsupervised machine learning": "🤖",
    "machine learning": "🤖",
    "deep learning": "🧠",
    "nlp": "💬",
    "llm": "🤖",
    "computer vision": "👁️",
    "reinforcement learning": "🎮",
    # Data
    "kpi design": "📊",
    "data visualization": "📈",
    "data modeling": "🗄️",
    "data analysis": "📊",
    "data science": "🔬",
    "data lakehouse": "🏠",
    "data warehouse": "🏗️",
    "big data": "📊",
    "big data processing": "📊",
    "statistics": "📐",
    "experiment design": "🧪",
    "experimentation": "🧪",
    "a/b testing": "🧪",
    "time series": "📈",
    "feature engineering": "🔧",
    "feature stores": "🗄️",
    "model governance": "🛡️",
    "model deployment": "🚀",
    "mlops": "⚙️",
    # Pipelines / Engineering
    "etl": "⚙️",
    "etl/elt": "⚙️",
    "streaming": "📡",
    "business intelligence": "📊",
    # Infraestructura / Xarxes
    "rfid": "📡",
    "aplicaciones rfid": "📡",
    "gis": "🗺️",
    "local area network": "🌐",
    "client-server environment": "🌐",
    "voip": "📞",
    "san": "💾",
    "servers": "🖥️",
    "routers": "🌐",
    "modems": "📡",
    # Suport / Gestió
    "help desk support": "🖥️",
    "software deployment": "🚀",
    "budgeting": "💰",
    "organizational strategic initiative": "📋",
}

def skill_icon_html(skill_name: str, size: int = 22) -> str:
    """Retorna l'emoji de la skill, o '' si no n'hi ha. Sense CDN — sempre es renderitza."""
    key = skill_name.lower().strip()
    emoji = _EMOJI.get(key)
    if not emoji:
        for k, v in _EMOJI.items():
            if k in key or key in k:
                emoji = v
                break
    if emoji:
        return f"<span style='font-size:{size}px;line-height:1'>{emoji}</span>"
    return ""
